from subprocess import Popen, PIPE
from waflib.Configure import conf
from waflib.extras.layout import Solution

def options(optCtx):
    optCtx.add_option('--mode', type='string',
            default='release', dest='mode',
	    help='Build mode, e.g. release, debug')
    optCtx.add_option('--platform', type='string',
            default='', dest='build_mode',
	    help='Build platform, e.g. 32bit, 64bit')

@conf
def check_hardware(self):
    self.load('cpuinfo')
    self.env.append_value('CXXFLAGS', ['-DLEVEL1_DCACHE_LINESIZE=%s' % self.find_dcache_line_size()])
    self.env.append_value('CXXFLAGS', ['-m%s' % self.find_pointer_size()])

def configure(confCtx):
    solution = Solution.fromContext(confCtx)
    confCtx.env.solution = solution
    confCtx.check_hardware()
    confCtx.env.append_value('CXXFLAGS', ['-Wall', '-Wextra', '-O2', '-ggdb',
	    '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', 
	    '-fno-builtin-free', '-pthread', '-Wl,-z,origin'])
